name: desingcode
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  sliding_up_panel: ^2.0.0+1
  firebase_core: ^3.8.1
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  assets:
    - assert/badges/
    - assert/certificates/
    - assert/fonts/
    - assert/icons/
    - assert/illustrations/
    - assert/images/
    - assert/logos/

  uses-material-design: true
